var SomaFunc = require('./soma');
var SubFunc = require('./sub');
var MultiFunc = require('./multi');
var DivFunc = require('./div');
require('./sub');
require('./multi');
require('./div');
console.log(SomaFunc(2,4));
console.log(SubFunc(2,4));
console.log(MultiFunc(2,4));
console.log(DivFunc(2,4));
